export const ACTIONS = {
  UPDATE_CALCULATION: "UPDATE_CALCULATION",
  UPDATE_RESULT: "UPDATE_RESULT",
  UPDATE_OPERATOR: "UPDATE_OPERATOR",
  CLEAR_ALL: "CLEAR_ALL",
  CLEAR_ENTRY: "CLEAR_ENTRY",
  SWITCH_POLARITY: "SWITCH_POLARITY",
  DO_CALCULATION: "DO_CALCULATION",
} as const;
